/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class TypeIncompatibilityConstraint extends Constraint {
  private transient long swigCPtr;

  protected TypeIncompatibilityConstraint(long cPtr, boolean cMemoryOwn) {
    super(mainJNI.TypeIncompatibilityConstraint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypeIncompatibilityConstraint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_TypeIncompatibilityConstraint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TypeIncompatibilityConstraint(RoutingModel model) {
    this(mainJNI.new_TypeIncompatibilityConstraint(RoutingModel.getCPtr(model), model), true);
  }

  public void post() {
    mainJNI.TypeIncompatibilityConstraint_post(swigCPtr, this);
  }

  public void initialPropagate() {
    mainJNI.TypeIncompatibilityConstraint_initialPropagate(swigCPtr, this);
  }

}
