/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.google.ortools.constraintsolver;

public class TypeIncompatibilityChecker {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TypeIncompatibilityChecker(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TypeIncompatibilityChecker obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mainJNI.delete_TypeIncompatibilityChecker(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TypeIncompatibilityChecker(RoutingModel model) {
    this(mainJNI.new_TypeIncompatibilityChecker(RoutingModel.getCPtr(model), model), true);
  }

  public boolean TemporalIncompatibilitiesRespectedOnVehicle(int vehicle, SWIGTYPE_p_std__functionT_long_long_flong_longF_t next_accessor) {
    return mainJNI.TypeIncompatibilityChecker_TemporalIncompatibilitiesRespectedOnVehicle(swigCPtr, this, vehicle, SWIGTYPE_p_std__functionT_long_long_flong_longF_t.getCPtr(next_accessor));
  }

  public boolean AllIncompatibilitiesRespectedOnVehicle(int vehicle, SWIGTYPE_p_std__functionT_long_long_flong_longF_t next_accessor) {
    return mainJNI.TypeIncompatibilityChecker_AllIncompatibilitiesRespectedOnVehicle(swigCPtr, this, vehicle, SWIGTYPE_p_std__functionT_long_long_flong_longF_t.getCPtr(next_accessor));
  }

}
